### ISSUE TITLE
start problem

### ISSUE THREAD

**Issue by fabian93** [Plata17/TouchCarPI#41]
pi@raspberrypi:~/TouchCarPI-master/touchcarpi/main $ python3 __main__.py
libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "__main__.py", line 30, in <module>
    main()
  File "__main__.py", line 27, in main
    controller.initialize()
  File "/home/pi/TouchCarPI-master/touchcarpi/main/GUI/GUIController.py", line 45, in initialize
    self.db = RAM_DB()
  File "/home/pi/TouchCarPI-master/touchcarpi/main/DB/RAM_DB.py", line 209, in __init__
    RAM_DB.instance = RAM_DB.__RAM_DB()
  File "/home/pi/TouchCarPI-master/touchcarpi/main/DB/RAM_DB.py", line 59, in __init__
    metaDataVLC = MetaDataVLC(self.pathFiles)
  File "/home/pi/TouchCarPI-master/touchcarpi/main/DB/MetaDataVLC.py", line 32, in __init__
    self.vlcInstance = vlc.Instance()
  File "/home/pi/TouchCarPI-master/touchcarpi/main/libs/vlc.py", line 1692, in __new__
    return libvlc_new(len(args), args)
  File "/home/pi/TouchCarPI-master/touchcarpi/main/libs/vlc.py", line 4175, in libvlc_new
    ctypes.c_void_p, ctypes.c_int, ListPOINTER(ctypes.c_char_p))
  File "/home/pi/TouchCarPI-master/touchcarpi/main/libs/vlc.py", line 254, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_new'

**Comment by rfernandezf** [comment]
Hi! Are you using the vlc.py and the .dll versions of the VLC lib that are included in the project, or you have downloaded newer versions?

I'm actually using some deprecated calls from the VLC lib so I strongly suggest you to use the versions I provide in the project.

Greetings!
